# Generated by Django 3.1.3 on 2020-12-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20201206_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
