# Generated by Django 3.1.3 on 2020-12-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20201206_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='shop_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
