# Generated by Django 3.1.3 on 2021-01-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_ingredientcategory_shop_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ingredient'},
        ),
    ]
