# Generated by Django 3.1.3 on 2021-03-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freezerstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeze_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='ingrediens', max_length=20)),
                ('name', models.CharField(default=None, max_length=50)),
                ('qty', models.IntegerField()),
                ('best_before', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
