# Generated by Django 3.1.3 on 2020-12-01 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipies', '0004_auto_20201201_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('foodplan_id', models.IntegerField(default=1)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipies.recipies')),
            ],
        ),
    ]
