# Generated by Django 3.1.3 on 2020-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_auto_20201201_1332'),
        ('foodplan', '0002_auto_20201201_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foodplan',
            new_name='Foodplans',
        ),
    ]
