# Generated by Django 3.1.3 on 2020-12-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_auto_20201201_1332'),
        ('foodplan', '0004_auto_20201201_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplans',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipies.recipies'),
        ),
    ]
