# Generated by Django 3.1.3 on 2020-12-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0005_auto_20201201_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplans',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
