# Generated by Django 3.1.3 on 2020-12-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0006_foodplans_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplans',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
