# Generated by Django 3.1.3 on 2020-12-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0007_foodplans_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodplanComplete',
            fields=[
                ('foodplan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodplans',
            name='complete',
        ),
    ]
