# Generated by Django 3.1.3 on 2020-12-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0008_auto_20201218_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodplanComplete',
            new_name='FoodplanStatus',
        ),
    ]
