# Generated by Django 3.1.3 on 2021-01-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0011_auto_20201218_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodplans',
            options={'verbose_name': 'Foodplan'},
        ),
    ]
