# Generated by Django 3.1.3 on 2021-01-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0012_auto_20210117_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplanstatus',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodplanstatus',
            name='foodplan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodplan.foodplans'),
        ),
    ]
