# Generated by Django 3.1.3 on 2021-01-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0013_auto_20210125_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodplanstatus',
            old_name='foodplan_id',
            new_name='foodplan',
        ),
    ]
