# Generated by Django 3.1.3 on 2021-01-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0020_recipeingredientsheading_place'),
        ('foodplan', '0014_auto_20210125_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodplans',
            name='foodplan_id',
        ),
        migrations.RemoveField(
            model_name='foodplans',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='foodplans',
            name='recipe',
        ),
        migrations.CreateModel(
            name='FoodplanRecipies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('foodplan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodplan.foodplans')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipies.recipies')),
            ],
        ),
    ]
