# Generated by Django 3.1.3 on 2021-01-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan', '0015_auto_20210125_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplans',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FoodplanStatus',
        ),
    ]
