# Generated by Django 3.1.3 on 2020-12-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201217_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ingredient_type',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
