# Generated by Django 3.1.3 on 2020-12-20 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_ingredientcategory_shop_order'),
        ('todo', '0005_auto_20201219_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ingredient_category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ingredients.ingredientcategory'),
        ),
    ]
