# Generated by Django 3.1.3 on 2021-01-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210125_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='source',
            new_name='shoppinglist_id',
        ),
    ]
