# Generated by Django 3.1.3 on 2021-01-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20210125_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
