# Generated by Django 3.1.3 on 2021-01-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_shoppinglist_source_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='shoppinglist_id',
            new_name='shoppinglist',
        ),
    ]
