# Generated by Django 3.1.3 on 2020-11-30 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('recipe_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipies.recipetypes')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInstructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=2000)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipies')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipies.ingredients')),
                ('measurement_unit', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='recipies.measurementunits')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipies')),
            ],
        ),
    ]
