# Generated by Django 3.1.3 on 2020-11-30 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_auto_20201130_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='recipe_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipies.recipetypes'),
        ),
    ]
