# Generated by Django 3.1.3 on 2020-12-04 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipies', '0006_ingredients_best_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredients.ingredients'),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
