# Generated by Django 3.1.3 on 2020-12-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0007_auto_20201204_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
