# Generated by Django 3.1.3 on 2020-12-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0008_auto_20201213_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, upload_to='photos/thumbnails/'),
        ),
    ]
