# Generated by Django 3.1.3 on 2020-12-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0010_auto_20201214_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', null=True, to='recipies.RecipeTags'),
        ),
    ]
