# Generated by Django 3.1.3 on 2020-12-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0011_auto_20201215_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='tags',
            field=models.ManyToManyField(default='', to='recipies.RecipeTags'),
        ),
    ]
