# Generated by Django 3.1.3 on 2020-12-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0013_auto_20201215_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='tags',
            field=models.ManyToManyField(to='recipies.RecipeTags'),
        ),
    ]
