# Generated by Django 3.1.3 on 2021-01-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0015_recipeingredients_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementunits',
            options={'verbose_name': 'Recipe measurement unit'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Recipe Ingredient'},
        ),
        migrations.AlterModelOptions(
            name='recipeinstructions',
            options={'verbose_name': 'Recipe instruction'},
        ),
        migrations.AlterModelOptions(
            name='recipetags',
            options={'verbose_name': 'Recipe tag'},
        ),
        migrations.AlterModelOptions(
            name='recipetypes',
            options={'verbose_name': 'Recipe type'},
        ),
        migrations.AlterModelOptions(
            name='recipies',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipies'},
        ),
        migrations.AddField(
            model_name='recipies',
            name='prep_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
