# Generated by Django 3.1.3 on 2021-01-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0017_auto_20210117_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeinstructions',
            name='is_bold',
            field=models.BooleanField(default=False),
        ),
    ]
