# Generated by Django 3.1.3 on 2021-01-20 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0018_recipeinstructions_is_bold'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredientsHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=300, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipies')),
            ],
            options={
                'verbose_name': 'Recipe Ingredient Heading',
            },
        ),
    ]
