# Generated by Django 3.1.3 on 2021-01-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0019_recipeingredientsheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredientsheading',
            name='place',
            field=models.IntegerField(default=1),
        ),
    ]
