# Generated by Django 3.1.3 on 2021-01-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0020_recipeingredientsheading_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
