# Generated by Django 3.1.3 on 2021-01-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0022_recipies_add_ons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_on', to='recipies.recipies')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipies.recipies')),
            ],
            options={
                'verbose_name': 'Recipe Add-ons',
            },
        ),
    ]
