# Generated by Django 3.1.3 on 2021-01-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0023_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='add_ons',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
