# Generated by Django 3.1.3 on 2021-02-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0025_auto_20210130_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
