# Generated by Django 3.1.3 on 2021-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0026_addons_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='qty_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
