# Generated by Django 3.1.3 on 2021-02-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0028_addons_preferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addons',
            name='preferred',
        ),
    ]
