# Generated by Django 3.1.3 on 2021-02-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0029_remove_addons_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='preferred_add_ons',
            field=models.ManyToManyField(blank=True, related_name='_recipies_preferred_add_ons_+', to='recipies.Recipies'),
        ),
    ]
